
name: Test Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *  
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation Framework with Maven
      run: mvn test -X -Dbroswer=chrome -DisLamdaTest=true -DisHeadless=false 


    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
            name: Test Logs
            path: logs/


    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v6.0.0
      with:
            name: screenshots
            path: screenshots/
            
    - name: Upload HTML Reports as Artifacts
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.6
      with:
            name: html-report
            path: report.html

    - name: Test Execution Status
      run: echo "Test Execution completed"
    - name: Copy Report to gitHub-Pages Folder
      if: always()

      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        cp -R screenshots/ public/extent-reports/screenshots/
        ls -l

    - name: Deploy
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.6
      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAT1234 }}
        clean: true
